package ai

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"strings"
	"time"
)

const (
	defaultOpenAICompatibleTimeout = 20 * time.Second
)

// ChatCompletionClient defines an OpenAI-compatible chat completion client.
type ChatCompletionClient interface {
	CreateChatCompletion(ctx context.Context, req ChatCompletionRequest) (ChatCompletionResponse, error)
}

// ChatCompletionRequest is the OpenAI-compatible chat completion request body.
type ChatCompletionRequest struct {
	Model       string        `json:"model"`
	Messages    []ChatMessage `json:"messages"`
	Tools       []ChatTool    `json:"tools,omitempty"`
	ToolChoice  string        `json:"tool_choice,omitempty"`
	Temperature float64       `json:"temperature,omitempty"`
}

// ChatCompletionResponse is the OpenAI-compatible chat completion response body.
type ChatCompletionResponse struct {
	ID      string                 `json:"id,omitempty"`
	Model   string                 `json:"model,omitempty"`
	Choices []ChatCompletionChoice `json:"choices"`
	Error   *ChatCompletionError   `json:"error,omitempty"`
}

// ChatCompletionChoice is one candidate completion choice.
type ChatCompletionChoice struct {
	Index        int         `json:"index"`
	Message      ChatMessage `json:"message"`
	FinishReason string      `json:"finish_reason,omitempty"`
}

// ChatCompletionError is a standardized API error payload.
type ChatCompletionError struct {
	Message string `json:"message"`
	Type    string `json:"type,omitempty"`
	Code    string `json:"code,omitempty"`
}

// ChatMessage is one chat message in the OpenAI-compatible schema.
type ChatMessage struct {
	Role       string         `json:"role"`
	Content    string         `json:"content,omitempty"`
	Name       string         `json:"name,omitempty"`
	ToolCallID string         `json:"tool_call_id,omitempty"`
	ToolCalls  []ChatToolCall `json:"tool_calls,omitempty"`
}

// ChatTool is one function tool definition.
type ChatTool struct {
	Type     string                 `json:"type"`
	Function ChatToolFunctionSchema `json:"function"`
}

// ChatToolFunctionSchema defines a callable function for tool calling.
type ChatToolFunctionSchema struct {
	Name        string         `json:"name"`
	Description string         `json:"description,omitempty"`
	Parameters  map[string]any `json:"parameters,omitempty"`
}

// ChatToolCall is one function call generated by the model.
type ChatToolCall struct {
	ID       string           `json:"id"`
	Type     string           `json:"type"`
	Function ChatFunctionCall `json:"function"`
}

// ChatFunctionCall carries tool name and JSON arguments string.
type ChatFunctionCall struct {
	Name      string `json:"name"`
	Arguments string `json:"arguments"`
}

type openAICompatibleClient struct {
	baseURL    string
	apiKey     string
	httpClient *http.Client
}

// NewOpenAICompatibleClient creates a client for OpenAI-compatible chat completion APIs.
func NewOpenAICompatibleClient(baseURL, apiKey string, timeout time.Duration) ChatCompletionClient {
	if timeout <= 0 {
		timeout = defaultOpenAICompatibleTimeout
	}
	return &openAICompatibleClient{
		baseURL: strings.TrimRight(strings.TrimSpace(baseURL), "/"),
		apiKey:  strings.TrimSpace(apiKey),
		httpClient: &http.Client{
			Timeout: timeout,
		},
	}
}

func (c *openAICompatibleClient) CreateChatCompletion(ctx context.Context, req ChatCompletionRequest) (ChatCompletionResponse, error) {
	if strings.TrimSpace(c.baseURL) == "" {
		return ChatCompletionResponse{}, fmt.Errorf("ai base url is empty")
	}
	if strings.TrimSpace(c.apiKey) == "" {
		return ChatCompletionResponse{}, fmt.Errorf("ai api key is empty")
	}

	payload, err := json.Marshal(req)
	if err != nil {
		return ChatCompletionResponse{}, fmt.Errorf("marshal chat completion request failed: %w", err)
	}

	url := c.baseURL + "/chat/completions"
	httpReq, err := http.NewRequestWithContext(ctx, http.MethodPost, url, bytes.NewReader(payload))
	if err != nil {
		return ChatCompletionResponse{}, fmt.Errorf("build chat completion request failed: %w", err)
	}
	httpReq.Header.Set("Authorization", "Bearer "+c.apiKey)
	httpReq.Header.Set("Content-Type", "application/json")

	resp, err := c.httpClient.Do(httpReq)
	if err != nil {
		return ChatCompletionResponse{}, fmt.Errorf("call chat completion failed: %w", err)
	}
	defer resp.Body.Close()

	rawBody, err := io.ReadAll(io.LimitReader(resp.Body, 4*1024*1024))
	if err != nil {
		return ChatCompletionResponse{}, fmt.Errorf("read chat completion response failed: %w", err)
	}

	var parsed ChatCompletionResponse
	if err := json.Unmarshal(rawBody, &parsed); err != nil {
		return ChatCompletionResponse{}, fmt.Errorf("decode chat completion response failed: %w", err)
	}

	if resp.StatusCode >= http.StatusBadRequest {
		if parsed.Error != nil && strings.TrimSpace(parsed.Error.Message) != "" {
			return ChatCompletionResponse{}, fmt.Errorf("chat completion http %d: %s", resp.StatusCode, parsed.Error.Message)
		}
		message := strings.TrimSpace(string(rawBody))
		if len(message) > 256 {
			message = message[:256]
		}
		if message == "" {
			message = "unknown error"
		}
		return ChatCompletionResponse{}, fmt.Errorf("chat completion http %d: %s", resp.StatusCode, message)
	}

	if parsed.Error != nil && strings.TrimSpace(parsed.Error.Message) != "" {
		return ChatCompletionResponse{}, fmt.Errorf("chat completion error: %s", parsed.Error.Message)
	}
	return parsed, nil
}
